[package]
name = "sentry-actix"
version = "0.1.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://github.com/getsentry/sentry-rust"
documentation = "https://docs.rs/sentry-actix"
description = """
Sentry client extension for actix-web
"""
build = "build.rs"

[dependencies]
actix-web = "0.6.13"
sentry = { version = "0.6.0", path = "../../" }
failure = "0.1.1"
uuid = "0.6.5"
