os: linux
language: rust
cache:
  cargo: true

git:
  depth: 1

branches:
  only:
    - master

script: make $SUITE

env: # Needed for allow_failures

matrix:
  include:
    - env: SUITE=check
      rust: "1.22.0"
    - env: SUITE=cargotest
      rust: "1.22.0"
    - env: SUITE=checkall
    - env: SUITE=cargotestall
    - os: osx
      env: SUITE=checkall
    - os: osx
      env: SUITE=cargotestall
    - env: SUITE=format-check
      install: rustup component add rustfmt-preview
    - env: SUITE=lint
      rust: nightly
      install: cargo install --force clippy
  allow_failures:
    - env: SUITE=lint
      rust: nightly

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/cba2c080-4305-11e8-bbec-0a580a280224/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
