os: linux
language: rust
cache:
  cargo: true

git:
  depth: 1

branches:
  only:
    - master
    - /^release\/.+$/

script: make $SUITE

matrix:
  include:
    - env: SUITE=format-check
    - env: SUITE=lint
    - env: SUITE=check
      rust: "1.31.0"
    - env: SUITE=cargotest
      rust: "1.31.0"
    - env: SUITE=checkall
    - env: SUITE=cargotestall
    - os: osx
      env: SUITE=checkall
    - os: osx
      env: SUITE=cargotestall
    - env: SUITE=travis-push-docs
      if: branch = master

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/cba2c080-4305-11e8-bbec-0a580a280224/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
