[package]
name = "sentry-types"
version = "0.1.0"
authors = ["Sentry <hello@sentry.io>"]

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
url = "1.6.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
serde_plain = "0.2.0"
