[workspace]
members = [
    "sentry",
    "sentry-actix",
    "sentry-anyhow",
    "sentry-backtrace",
    "sentry-contexts",
    "sentry-core",
    "sentry-debug-images",
    "sentry-log",
    "sentry-panic",
    "sentry-slog",
    "sentry-tracing",
    "sentry-types",
]
