[package]
name = "sentry"
version = "0.13.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://github.com/getsentry/sentry-rust"
documentation = "https://getsentry.github.io/sentry-rust"
description = """
Sentry (getsentry.com) client for rust ;)
"""
build = "build.rs"
edition = "2018"
autoexamples = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["with_client_implementation", "with_panic", "with_failure", "with_log", "with_env_logger", "with_device_info", "with_rust_info"]
with_client_implementation = ["reqwest", "im", "url", "with_backtrace"]
with_backtrace = ["backtrace", "regex"]
with_panic = ["with_backtrace"]
with_failure = ["failure", "with_backtrace"]
with_log = ["log", "with_backtrace"]
with_debug_to_log = ["log"]
with_env_logger = ["with_log", "env_logger"]
with_error_chain = ["error-chain", "with_backtrace"]
with_device_info = ["libc", "hostname", "uname", "with_client_implementation"]
with_rust_info = ["rustc_version", "with_client_implementation"]
with_debug_meta = ["findshlibs", "goblin", "memmap", "with_client_implementation"]
with_test_support = []

[dependencies]
backtrace = { version = "0.3.13", optional = true }
url = { version = "1.7.2", optional = true }
failure = { version = "0.1.5", optional = true }
log = { version = "0.4.6", optional = true, features = ["std"] }
sentry-types = "0.9.0"
env_logger = { version = "0.6.0", optional = true }
reqwest = { version = "0.9.6", optional = true }
lazy_static = "1.2.0"
regex = { version = "1.1.0", optional = true }
error-chain = { version = "0.12.0", optional = true }
im = { version = "12.2.0", optional = true }
libc = { version = "0.2.46", optional = true }
hostname = { version = "0.1.5", optional = true }
findshlibs = { version = "0.4.0", optional = true }
rand = "0.6.4"
httpdate = "0.3.2"

[target."cfg(not(windows))".dependencies]
uname = { version = "0.1.1", optional = true }

[target."cfg(unix)".dependencies]
goblin = { version = "0.0.19", default-features = false, features = ["elf32", "elf64", "endian_fd", "std"], optional = true }
memmap = { version = "0.7.0", optional = true }

[build-dependencies]
rustc_version = { version = "0.2.3", optional = true }

[dev-dependencies]
failure_derive = "0.1.5"
pretty_env_logger = "0.3.0"
actix-web = { version = "0.7.17", default-features = false }

[[example]]
name = "error-chain-demo"
required-features = ["with_error_chain"]

[workspace]
members = [".", "integrations/sentry-actix"]

[patch.crates-io]
findshlibs = { git = "https://github.com/getsentry/findshlibs", branch = "feature/add-is-code" }
