[package]
name = "sentry"
version = "0.5.2"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://github.com/getsentry/sentry-rust"
documentation = "https://docs.rs/sentry"
description = """
Sentry (getsentry.com) client for rust ;)
"""
build = "build.rs"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["with_client_implementation", "with_panic", "with_failure", "with_log", "with_device_info", "with_rust_info"]
with_client_implementation = ["reqwest", "im", "url", "with_backtrace"]
with_backtrace = ["backtrace", "regex"]
with_panic = ["with_backtrace"]
with_failure = ["failure", "with_backtrace"]
with_log = ["log", "with_backtrace"]
with_error_chain = ["error-chain", "with_backtrace"]
with_device_info = ["libc", "hostname", "uname", "with_client_implementation"]
with_rust_info = ["rustc_version", "with_client_implementation"]
with_debug_meta = ["findshlibs", "with_client_implementation"]
with_shim_api = []

[dependencies]
backtrace = { version = "0.3.8", optional = true }
url = { version = "1.7.0", optional = true }
failure = { version = "0.1.1", optional = true }
log = { version = "0.4.1", optional = true }
serde = "1.0.64"
serde_json = "1.0.19"
sentry-types = "0.5.2"
reqwest = { version = "0.8.6", optional = true }
uuid = { version = "0.6.5", features = ["v4"] }
lazy_static = "1.0.1"
regex = { version = "1.0.0", optional = true }
error-chain = { version = "0.11.0", optional = true }
im = { version = "10.2.0", optional = true }
libc = { version = "0.2.41", optional = true }
hostname = { version = "0.1.5", optional = true }
findshlibs = { version = "0.4.0", optional = true }

[target."cfg(not(windows))".dependencies]
uname = { version = "0.1.1", optional = true }

[build-dependencies]
rustc_version = { version = "0.2.2", optional = true }

[dev-dependencies]
failure_derive = "0.1.1"
pretty_env_logger = "0.2.3"

[[example]]
name = "error-chain-demo"
required-features = ["with_error_chain"]

# TODO: Remove these once autoexamples are stable
[[example]]
name = "failure-demo"
[[example]]
name = "log-demo"
[[example]]
name = "message-demo"
[[example]]
name = "panic-demo"
[[example]]
name = "thread-demo"
