[package]
name = "sentry-types"
version = "0.3.4"
license = "Apache-2.0"
description = "Common reusable types for implementing the sentry.io protocol."
homepage = "https://sentry.io/"
repository = "https://github.com/getsentry/rust-sentry-types"
documentation = "https://docs.rs/sentry-types"
keywords = ["sentry", "protocol"]
readme = "README.md"
authors = ["Sentry <hello@sentry.io>"]
exclude = [
    ".vscode/**/*",
    "scripts/**/*"
]

[features]
default = ["with_protocol", "with_serde"]
with_protocol = ["with_serde"]
with_serde = ["serde", "serde_derive", "serde_json", "url_serde", "chrono/serde", "uuid/serde", "linked-hash-map/serde_impl", "debugid/with_serde"]

[badges]
travis-ci = { repository = "getsentry/rust-sentry-types" }

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
url = "1.7.0"
serde = { version = "1.0.50", optional = true }
serde_derive = { version = "1.0.50", optional = true }
serde_json = { version = "1.0.17", features = ["preserve_order"], optional = true }
url_serde = { version = "0.2.0", optional = true }
chrono = "0.4.2"
uuid = { version = "0.6.3", features = ["v4"] }
linked-hash-map = "0.5.1"
debugid = "0.2.0"
