[package]
name = "sentry-actix"
version = "0.24.2"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://sentry.io/welcome/"
description = """
Sentry client extension for actix-web 3.
"""
edition = "2018"

[dependencies]
sentry-core = { version = "0.24.2", path = "../sentry-core", default-features = false, features = ["client"] }
actix-web = { version = "3", default-features = false }
futures-util = { version = "0.3.5", default-features = false }

[dev-dependencies]
sentry = { path = "../sentry", features = ["test"] }
actix-rt = "2.1.0"
futures = "0.3"
