[package]
name = "sentry-actix"
version = "0.28.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://sentry.io/welcome/"
description = """
Sentry client extension for actix-web 3.
"""
edition = "2021"
rust-version = "1.60"

[dependencies]
actix-web = { version = "4", default-features = false }
futures-util = { version = "0.3.5", default-features = false }
sentry-core = { version = "0.28.0", path = "../sentry-core", default-features = false, features = ["client"] }

[dev-dependencies]
actix-web = { version = "4" }
futures = "0.3"
sentry = { path = "../sentry", features = ["test"] }
tokio = { version = "1.0", features = ["full"] }
