[package]
name = "sentry-contexts"
version = "0.46.1"
authors = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
homepage = { workspace = true }
description = """
Sentry integration for os, device, and rust contexts.
"""
build = "build.rs"
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
sentry-core = { version = "0.46.1", path = "../sentry-core" }
libc = "0.2.66"
hostname = "0.4"

[target."cfg(not(windows))".dependencies]
uname = "0.1.1"

[target."cfg(windows)".dependencies]
os_info = "3.5.0"

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
sentry = { path = "../sentry", default-features = false, features = ["test"] }
