[package]
name = "sentry-contexts"
version = "0.31.2"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://sentry.io/welcome/"
description = """
Sentry integration for os, device, and rust contexts.
"""
build = "build.rs"
edition = "2021"
rust-version = "1.66"

[dependencies]
sentry-core = { version = "0.31.2", path = "../sentry-core" }
libc = "0.2.66"
hostname = "0.3.0"

[target."cfg(not(windows))".dependencies]
uname = "0.1.1"

[target."cfg(windows)".dependencies]
os_info = "3.5.0"

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
sentry = { path = "../sentry", default-features = false, features = ["test"] }
