[package]
name = "sentry-tracing"
version = "0.23.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://sentry.io/welcome/"
description = """
Sentry integration for tracing and tracing-subscriber crates.
"""
edition = "2018"

[dependencies]
sentry-core = { version = "0.23.0", path = "../sentry-core" }
tracing-core = "0.1"
tracing-subscriber = { version = "0.3.1", default-features = false, features = ["std"] }

[dev-dependencies]
log = "0.4"
sentry = { path = "../sentry", default-features = false, features = ["test"] }
tracing = "0.1"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros", "time"] }
