[package]
name = "sentry-opentelemetry"
version = "0.39.0"
authors = ["Sentry <hello@sentry.io>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://sentry.io/welcome/"
description = """
Sentry integration for OpenTelemetry.
"""
edition = "2021"
rust-version = "1.81"

[package.metadata.docs.rs]
all-features = true

[dependencies]
sentry-core = { version = "0.39.0", path = "../sentry-core", features = [
    "client",
] }
opentelemetry = { version = "0.29.0", default-features = false }
opentelemetry_sdk = { version = "0.29.0", default-features = false, features = [
    "trace",
] }

[dev-dependencies]
sentry = { path = "../sentry", features = ["test", "opentelemetry"] }
sentry-core = { path = "../sentry-core", features = [ "test" ] }
opentelemetry_sdk = { version = "0.29.0", default-features = false, features = [
    "trace",
    "testing",
] }
