[package]
name = "sentry-slog"
version = "0.19.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://sentry.io/welcome/"
description = """
Sentry integration for the slog crate.
"""
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[dependencies]
sentry-core = { version = "0.19.0", path = "../sentry-core" }
slog = "2.5.2"

[dev-dependencies]
sentry = { version = "0.19.0", path = "../sentry", default-features = false, features = ["test"] }
