[package]
name = "sentry-anyhow"
version = "0.22.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://sentry.io/welcome/"
description = """
Sentry integration for anyhow.
"""
edition = "2018"

[features]
backtrace = ["anyhow/backtrace"]

[dependencies]
sentry-backtrace = { version = "0.22.0", path = "../sentry-backtrace" }
sentry-core = { version = "0.22.0", path = "../sentry-core" }
anyhow = "1.0.39"

[dev-dependencies]
sentry = { version = "0.22.0", path = "../sentry", default-features = false, features = ["test"] }
