[package]
name = "sentry-anyhow"
version = "0.31.3"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://sentry.io/welcome/"
description = """
Sentry integration for anyhow.
"""
edition = "2021"
rust-version = "1.66"

[features]
default = ["backtrace"]
backtrace = ["anyhow/backtrace"]

[dependencies]
sentry-backtrace = { version = "0.31.3", path = "../sentry-backtrace" }
sentry-core = { version = "0.31.3", path = "../sentry-core" }
anyhow = "1.0.39"

[dev-dependencies]
sentry = { path = "../sentry", default-features = false, features = ["test"] }
